config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews

  root 'reviews#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
  geocoded_by :address   # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates

  validates :review_date, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :score, presence: true

  def review_infowindow
    "<h3><a href='#{url}' target='_blank'>#{name}</a></h3>
    <strong>#{address}</strong></br>
    <strong>Review Date: </strong>#{review_date}</br>
    <strong>Score: </strong>#{score}</br>
    <strong>Guests: </strong>#{guest}"
  end

  def review_marker_picture
    ({
      :url     => "/assets/El_pres.jpg",
      :width   => 26,
      :height  => 34
    })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @reviews = Review.all.order('review_date DESC')

    @hash = Gmaps4rails.build_markers(@reviews) do |review, marker|
      marker.lat review.latitude
      marker.lng review.longitude
      marker.title review.name
      marker.json data: { id: review.id }
      marker.infowindow review.review_infowindow
      marker.picture review.review_marker_picture
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    @reviews = Review.all
    @review = Review.create(review_params)
  end

  def update
    @reviews = Review.all
    @review = Review.find(params[:id])

    @review.update_attributes(review_params)
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
       format.html { redirect_to index }
       format.json { head :no_content }
       format.js   { render :layout => false }
    end
  end

  private
    # def sortable_columns
    #   ["review_date", "name", "address", "score"]
    # end
    #
    # def sort_column
    #   sortable_columns.include?(params[:column]) ? params[:column] : "review_date"
    # end
    #
    # def sort_direction
    #   %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    # end

    def set_review
      @review = Review.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:review_date, :name, :address, :score, :guest, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  # def sort_link(column, title = nil)
  #   title ||= column.titleize
  #   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  #   icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
  #   icon = column == sort_column ? icon : ""
  #   link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'shared/navigation' %>

<%= yield %>

</body>
</html>

app/views/reviews/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Delete Review</h3>
    </div>
    <div class="modal-body">
      <ul class="errors"></ul>
      Are you sure you wish to delete <b><%= @review.name %></b>?
    </div>
    <div class="modal-footer">
      <%= link_to "Yes, Delete This Review", product_path(@review), method: :delete, remote: true, class: "btn btn-danger" %>
      <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
    </div>
  </div>
</div>

app/views/reviews/_edit.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3><%= "Editing #{@review.name}" %></h3>
      </div>
        <%= render 'form' %>
    </div>
  </div>

app/views/reviews/_form.html.erb
  <div class="modal-body">
    <%= form_for(@review, remote: true, html: { style: "display:inline;" }) do |f| %>
      <ul class="errors"></ul>
      <div class="form-group">
        <%= f.label :review_date %><br>
        <%= f.date_field :review_date, as: :date_picker, :value => Time.now.strftime('%Y-%m-%d') %>
      </div>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder: "Enter name of pizza place" %>
      </div>
      <div class="form-group">
        <%= f.label :address %><br>
        <%= f.text_field :address, placeholder: "Enter full address (street, city, state). Ex: 800 6th Ave, New York, NY" %>
      </div>
      <div class="form-group">
        <%= f.label :score %><br>
        <%= f.text_field :score, placeholder: "Enter review score"%>
      </div>
      <div class="form-group">
        <%= f.label :url %><br>
        <%= f.text_field :url, placeholder: "Enter url for review post/video" %>
      </div>
      <div class="form-group">
        <%= f.label :guest %><br>
        <%= f.text_field :guest, placeholder: "Enter guest(s) that participated in the review" %>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>

app/views/reviews/_index.html.erb
<% @reviews.each do |review| %>
  <tr>
    <td width="15%"><%= review.review_date %></td>
    <td width="25%" data-toggle="tooltip" data-placement="top" title="Click to see on map" class="review_name" data-id="<%= review.id %>"><a><%= review.name %></a></td>
    <td width="30%"><%= review.address %></td>
    <td width="5%"><%= review.score %></td>
    <td width="15%"><%= review.guest %></td>
    <td width="10%"><%= link_to "Video", review.url, target: "_blank" %></td>
    <% if current_user.try(:admin?) %>
    <% end %>
    <td width="3%">
      <% if current_user.try(:admin?) %>
        <%= link_to edit_review_path(review), remote: true do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
      <% end %>
    </td>
    <td>
      <% if current_user.try(:admin?) %>
        <%= link_to review, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_review", remote: true do %>
          <i class="glyphicon glyphicon-remove-circle" ></i>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/reviews/_new.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1>New Review</h1>
      </div>
        <%= render 'form' %>
    </div>
  </div>

app/views/reviews/_review.html.erb
<tr>
  <td><%= review.review_date %></td>
  <td><%= link_to review.name, review.url, target: "_blank" %></td>
  <td><%= review.address %></td>
  <td><%= review.score %></td>
  <td><%= link_to 'Edit', edit_review_path(review), remote: true, class: "btn btn-default" %></td>
  <td><%= link_to 'Delete', review_delete_path(review), remote: true, class: "btn btn-danger" %></td>
</tr>

app/views/reviews/_save.js.erb
$("ul.errors").html("")
<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".review-index").html("<%= escape_javascript(render 'index') %>")
  $("#review-modal").modal("hide")
<% end %>

app/views/reviews/create.js.erb
<%= render "save" %>
// buildMap();

app/views/reviews/destroy.js.erb
$('.delete_review').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
  //  $('#map').empty();
  //  buildMap();
});

app/views/reviews/edit.js.erb
$("#review-modal").html("<%= escape_javascript(render 'edit') %>")
$("#review-modal").modal("show")

app/views/reviews/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyASi9uo5ndtZsJtdCdToyps9RasgDwYvsg&amp;v=3&amp;sensor=false&amp;libraries=geometry" type="text/javascript" data-turbolinks-eval=false></script>
<!-- AIzaSyASi9uo5ndtZsJtdCdToyps9RasgDwYvsg -->

<div class="container-fluid">
  <div class="row">
    <% if @reviews.any? %>
      <div class="col-md-12" id="mapDiv">
        <h2>One Bite: You Know The Rules...</h2>
        <h4>Click on a marker to see more details for that review</h4>
        <br/>
        <div id="map"></div>
        <script>
          function buildMap() {
            function bindReviewToMarker($li, marker){
              $li.on('click', function(){
                handler.getMap().setZoom(16);
                marker.setMap(handler.getMap()); //because clusterer removes map property from marker
                marker.panTo();
                google.maps.event.trigger(marker.getServiceObject(), 'click');
                $('html, body').animate({
                    scrollTop: $("#map").offset().top
                }, 1000);
              })
            };

            function bindClick(review_array) {
              _.each(review_array, function(json){
                var id = json.data.id;
                var review = $(".review_name[data-id='" + id + "']");
                bindReviewToMarker(review, json.marker);
              });
            };

            var review_array = <%=raw @hash.to_json %>
            var handler = Gmaps.build('Google');
            handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
              markers = handler.addMarkers(review_array);

              _.each(review_array, function(json, index){
                json.marker = markers[index];
              });

              bindClick(review_array);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
            });
          }

          buildMap();

        </script>
      </div>
    <% end %>
  </div>
  <hr />
  <div class="row tableNote">
    <div class="col-md-12">
      <div id="tableNoteContainer">
        <h4>
          Click on the name of a place to see where it is on the map. Click on a table header to sort by that header.
        </p>
      </div>
    </div>
  </div>
  <div class="row tableDiv">
    <div class="col-md-12">
      <div id="tableContainer" class="tableContainer">
        <table class="table table-condensed table-hover scrollTable sortable" id="reviews">
          <thead class="fixedHeader">
            <tr>
              <th width="14.5%"data-toggle="tooltip" data-placement="top" title="Click to sort by date">Review Date</th>
              <th width="23.75%"data-toggle="tooltip" data-placement="top" title="Click to sort by name">Name</th>
              <th width="28%" data-toggle="tooltip" data-placement="top" title="Click to sort by address">Address</th>
              <th width="5%" data-toggle="tooltip" data-placement="top" title="Click to sort by score">Score</th>
              <th width="15%" data-toggle="tooltip" data-placement="top" title="Click to sort by guest">Guests</th>
              <th width="10%"></th>
              <th width="5%"></th>
            </tr>
          </thead>

          <tbody class="review-index scrollContent">
            <%= render "index" %>
          </tbody>
        </table>
      </div>
      <hr />

      <div class="newReviewDiv">
          <% if current_user.try(:admin?) %>
            <%= link_to 'New Review', new_review_path, remote: true, class: "btn btn-success new_review_btn" %><br/ >
          <% end %>

      </div>

      <div id="review-modal" class="modal fade">
      </div>
      <br>
    </div>
  </div>
</div>

app/views/reviews/new.js.erb
$("#review-modal").html("<%= escape_javascript(render 'new') %>")
$("#review-modal").modal("show")

app/views/reviews/update.js.erb
<%= render "save" %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= image_tag 'logo.png' %>
      </a>
    </div>
    <div class="collapse navbar-collapse"> 
      <p class="navbar-text navbar-right">
        <% if current_user.try(:admin?) %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "btn btn-destroy") %>
        <% end %>
      </p>
     </div>
  </div>
</nav>